### ISSUE TITLE
Make a change in entering data into the table

### ISSUE THREAD

**Issue by witkowskidawid** [Davasny/mech_pk_free_time_finder#1]
https://github.com/Davasny/mech_pk_free_time_finder/blob/03c3c5d6bee593821c5848d05633145b12894db5/finder/models/TimetableFinder.py#L77
 
Data should be split into two tables but in this code, the two tables are duplicated without separating lessons.

**Comment by Davasny** [comment]
Fixed in https://github.com/Davasny/mech_pk_free_time_finder/commit/e2435b098f2a1084337026c56b64244fe09c62bd
